### ISSUE TITLE
systemd version fails to parse correctly on Debian 10

### ISSUE THREAD

**Issue by lae** [cloudalchemy/ansible-blackbox-exporter#57]
**What happened?**

I'm deploying this on a Debian 10 host and the service fails to use the ICMP probe. Upon investigating, it looks like there is logic in `templates/blackbox_exporter.service.j2` to add `AmbientCapabilities=CAP_NET_RAW` (and friends) if the version is greater than 232—however, this fails to get templated correctly because the resulting fact has parentheses:

```
TASK [cloudalchemy.blackbox-exporter : Set systemd version fact] *****************************************
ok: [core-dev-monitor] => {
    "ansible_facts": {
        "blackbox_exporter_systemd_version": "(241)"
    },
    "changed": false
}
```

The version output appears to have changed:

```
$ systemctl --version
systemd 241 (241)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

A quick search for more info led me to https://github.com/saltstack/salt/issues/51745, so I guess it's a change starting from this version of systemd. Seems we could use either the output from `udevadm --version` or (the approach Salt's taken) a regex match `\w+ ([0-9]+)`.

**Environment**

* Role version:

    0.8.0

* Ansible version information:

```
ansible 2.9.2
  config file = /home/lae/work/fressets/src/testenv-management/ansible.cfg
  configured module search path = ['/home/lae/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.0 (default, Oct 23 2019, 18:51:26) [GCC 9.2.0]
```

* Variables:

```
blackbox_exporter_configuration_modules:
  icmp:
    prober: icmp
    timeout: 2s
```

**Comment by paulfantom** [comment]
We hit the same problem in node_exporter role. Regex solution was used in https://github.com/cloudalchemy/ansible-node-exporter/blob/1357ea40d3bfd6aa60599f75ed05de89cb417380/tasks/preflight.yml#L17

Would you mind creating a PR with similar fix?

**Comment by lae** [comment]
Sure thing.
