### ISSUE TITLE
ICMP probes fails on older systemd 

### ISSUE THREAD

**Issue by elcomtik** [cloudalchemy/ansible-blackbox-exporter#64]
**What happened?**
ICMP probbes was not successful because of error : "caller=main.go:119 module=icmp target={host_xyz] level=error msg="Error listening to socket" err="listen ip4:icmp 0.0.0.0: socket: operation not permitted""

**Did you expect to see some different?**
Probe success

**How to reproduce it (as minimally and precisely as possible)**:
make request to exporter, in debug mode:
http:[exporter_host]:9115/probe?target=[probed_host]&module=icmp&debug=true'

**Environment**
CentOS Linux release 7.7.1908 (Core)
Systemd version: 219

* Role version:
0.9.0

* Role variables
blackbox_exporter_configuration_modules:
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4

**Anything else we need to know?**:

- I tried to run exporter as root in shell (not as systemd service) and this way probe succeeded. I suggest this is systemd setting issue
- I have also running smokeping prober installed by https://github.com/cloudalchemy/ansible-smokeping_prober, it runs as systemd service without problems
- I tried set additional setting(like smokeping prober have) to blackbox service and it started to work. 
  CapabilityBoundingSet=CAP_NET_RAW
  AmbientCapabilities=CAP_NET_RAW
  PrivateDevices=true

- I suggest that role should handle correctly systems with older systemd.I see that template has conditional for newer one which adds additional setting, but older ones are missing some supplementary settings to allow ICMP pings

**Comment by elcomtik** [comment]
related to https://github.com/cloudalchemy/ansible-blackbox-exporter/pull/45

**Comment by elcomtik** [comment]
I just tested that only setting AmbientCapabilities=CAP_NET_RAW is suffieciet to work properly. Systemd report version 219, however it looks like RHEL7 (Centos7 similarly) suport AmbientCapabilities, from version 7.3 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/7.3_release_notes/index 

I think that conditional should consider this anomaly somehow

**Comment by paulfantom** [comment]
We can just set it outside of the ansible conditional and let systemd handle this. In such case older systemd versions will produce a warning about unknown parameter in service file, but service should start without problems.

Could you create a PR with such solution?

**Comment by elcomtik** [comment]
Yes i can make PR for this solution

I have another idea, what about introducing new test scenarios which will use command 'systemd-analyze verify [systemd.service]' and make service templates distribution specific? I just looked for result of this verify command and there are plenty of warnning for services managed by cloudalchemy ansible roles:
[/etc/systemd/system/smokeping_prober.service:8] Unknown lvalue 'StartLimitInterval' in section 'Unit'
[/etc/systemd/system/smokeping_prober.service:9] Unknown lvalue 'StartLimitIntervalSec' in section 'Unit'
[/etc/systemd/system/smokeping_prober.service:24] Unknown lvalue 'LockPersonality' in section 'Service'
[/etc/systemd/system/smokeping_prober.service:26] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
[/etc/systemd/system/smokeping_prober.service:30] Unknown lvalue 'RemoveIPC' in section 'Service'
[/etc/systemd/system/smokeping_prober.service:31] Unknown lvalue 'RestrictSUIDSGID' in section 'Service'
[/etc/systemd/system/blackbox_exporter.service:7] Unknown lvalue 'StartLimitInterval' in section 'Unit'
[/etc/systemd/system/blackbox_exporter.service:8] Unknown lvalue 'StartLimitIntervalSec' in section 'Unit'
[/etc/systemd/system/blackbox_exporter.service:24] Unknown lvalue 'LockPersonality' in section 'Service'
[/etc/systemd/system/blackbox_exporter.service:26] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
[/etc/systemd/system/blackbox_exporter.service:29] Unknown lvalue 'RemoveIPC' in section 'Service'
[/etc/systemd/system/blackbox_exporter.service:30] Unknown lvalue 'RestrictSUIDSGID' in section 'Service'
[/etc/systemd/system/node_exporter.service:8] Unknown lvalue 'StartLimitInterval' in section 'Unit'
[/etc/systemd/system/alertmanager.service:7] Unknown lvalue 'StartLimitInterval' in section 'Unit'
[/etc/systemd/system/alertmanager.service:8] Unknown lvalue 'StartLimitIntervalSec' in section 'Unit'
[/etc/systemd/system/alertmanager.service:21] Failed to parse capability in bounding/ambient set, ignoring: CAP_SET_UID
[/etc/systemd/system/alertmanager.service:22] Unknown lvalue 'LockPersonality' in section 'Service'
[/etc/systemd/system/alertmanager.service:24] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
[/etc/systemd/system/alertmanager.service:28] Unknown lvalue 'RemoveIPC' in section 'Service'
[/etc/systemd/system/alertmanager.service:29] Unknown lvalue 'RestrictSUIDSGID' in section 'Service'
[/etc/systemd/system/prometheus.service:16] Failed to parse capability in bounding/ambient set, ignoring: CAP_SET_UID
[/etc/systemd/system/prometheus.service:18] Unknown lvalue 'LockPersonality' in section 'Service'
[/etc/systemd/system/prometheus.service:20] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
[/etc/systemd/system/prometheus.service:24] Unknown lvalue 'RemoveIPC' in section 'Service'
[/etc/systemd/system/prometheus.service:25] Unknown lvalue 'RestrictSUIDSGID' in section 'Service'

It wold be nice to have services without warning and tested for bugs in CI pipeline

**Comment by paulfantom** [comment]
I assume this is on RHEL system? Because if so, then this is due to the fact that Red Hat is backporting fixes and features to previous systemd versions. This in turn results in incorrect assignments of systemd features with version (like having ability to set `AmbientCapabilities` in systemd 219 even though it was introduced in systemd 232). So in case of RHEL we cannot rely simply on getting version of systemd. Fortunatelly systemd handles this gracefully.

For me, this is fine and if service is working I don't think we need to complicate tests even more and get into checking if a systemd feature is supported in some systemd version. Especially that every feature was checked against https://github.com/systemd/systemd/blob/master/NEWS to find out when it was added.

---
> I have another idea, what about introducing new test scenarios which will use command 'systemd-analyze verify [systemd.service]' and make service templates distribution specific? 

This won't work unless we make logic behind setting systemd features more complicated than just checking systemd version.

---
> make service templates distribution specific

No. We want as few distro-specific things as possible. Essentially if something is not necessary to be distro-specific then it won't be accepted/implemented. Reason behind this is simple - there will always be someone who wants to add another distro to supported ones and this increases maintenance toll on org.

**Comment by elcomtik** [comment]
I understand you don't want to add too much code and make role as simple as possible. I just thought that supported distributions (ones which are mentioned in meta) should have tuned services in such way it wouldn't throw any unnecessary warnings. 

However the solution which you proposed (to put AmbientCapabilities=CAP_NET_RAW outside conditional) works for me and I will make PR soon.
