### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by appliedprivacy** [cloudalchemy/ansible-blackbox-exporter#68]
**What is missing?**

Unlike other cloudalchemy roles, this role has no offline support, would be great to
have this here as well.

https://github.com/cloudalchemy/ansible-prometheus/issues/296

**Comment by paulfantom** [comment]
I am open to PRs which will implement it. Reference PRs are in https://github.com/cloudalchemy/ansible-alertmanager/pull/83 and https://github.com/cloudalchemy/ansible-prometheus/pull/239

**Comment by appliedprivacy** [comment]
If there is no good reason to keep the binary writable to the user running the service I'll change that to root (task: propagate blackbox exporter binary)

**Comment by paulfantom** [comment]
> If there is no good reason to keep the binary writable to the user running the service I'll change that to root

`root` seems good to me

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
