### ISSUE TITLE
RestrictSUIDSGID not supported in Debian buster

### ISSUE THREAD

**Issue by kmille** [cloudalchemy/ansible-blackbox-exporter#75]
The systemd unit file contains `RestrictSUIDSGID=true`. The `RestrictSUIDSGID` feature came with [systemd 242](https://github.com/systemd/systemd/blob/master/NEWS#L23309), Debian buster still uses [systemd 241](https://packages.debian.org/buster/systemd) which leads to the following warnings:
Dec 17 09:00:07 hostnamev systemd[1]: /etc/systemd/system/blackbox_exporter.service:24: Unknown lvalue 'RestrictSUIDSGID' in section 'Service', ignoring

**Comment by paulfantom** [comment]
Discussion in https://github.com/cloudalchemy/ansible-prometheus/issues/324
