### ISSUE TITLE
PIDfile in unit file leads to warnings 

### ISSUE THREAD

**Issue by kmille** [cloudalchemy/ansible-blackbox-exporter#76]
**What happened?**
Dec 19 15:08:17 hostname systemd[1]: blackbox_exporter.service: Can't open PID file /run/blackbox_exporter.pid (yet?) after reload: No such file or directory

**Environment**
Debian Buster
* Role version:
master

I recommend just removing the line. I don't think there is a PID file of blackbox_exporter.

**Comment by paulfantom** [comment]
That makes sense. Could you create a PR to remove `PIDFile=` from https://github.com/cloudalchemy/ansible-blackbox-exporter/blob/3cd8b92c65a870588ae6d5fd505e028f5e234e6f/templates/blackbox_exporter.service.j2#L10 ?
