### ISSUE TITLE
"Ensure blackbox exporter binary has cap_net_raw capability" task fails on Debian 11

### ISSUE THREAD

**Issue by supaflyster** [cloudalchemy/ansible-blackbox-exporter#82]
**What happened?**
Task "Ensure blackbox exporter binary has cap_net_raw capability" on re-run with 
 FAILED! => {"changed": false, "msg": "Unable to get capabilities of /usr/local/bin/blackbox_exporter", "stderr": "", "stderr_lines": [], "stdout": "/usr/local/bin/blackbox_exporter cap_net_raw=ep", "stdout_lines": ["/usr/local/bin/blackbox_exporter cap_net_raw=ep"]}

**Did you expect to see some different?**
Task is successful

**How to reproduce it (as minimally and precisely as possible)**:
Install blackbox exporter with the role, an re-run install playbook again. If blackbox_exporter binary is installed and capability is set, on second run this check will fail.

**Environment**
Target: Debian 11, Control: Ansible AWX with Ansible 2.9
* Role version:
src: git+https://github.com/cloudalchemy/ansible-blackbox-exporter.git
version: "1.0.0"

* Ansible version information:

   `ansible --version`
  ansible 2.9.18
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/lib/awx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 19 2021, 05:13:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

* Variables:

* Ansible playbook execution Logs:

TASK [cloudalchemy.ansible-blackbox-exporter : Ensure blackbox exporter binary has cap_net_raw capability] ***
fatal: [redacted]: FAILED! => {"changed": false, "msg": "Unable to get capabilities of /usr/local/bin/blackbox_exporter", "stderr": "", "stderr_lines": [], "stdout": "/usr/local/bin/blackbox_exporter cap_net_raw=ep", "stdout_lines": ["/usr/local/bin/blackbox_exporter cap_net_raw=ep"]}

**Anything else we need to know?**:
In the task, capability check is configured for "cap_net_raw+ep" which is true on Debian  10, but in Debian 11 output is different.

Output of getcap from Debian 10:
```
getcap /usr/local/bin/blackbox_exporter
/usr/local/bin/blackbox_exporter = cap_net_raw+ep

```
Output of getcap from Debain 11:
```
getcap /usr/local/bin/blackbox_exporter
/usr/local/bin/blackbox_exporter cap_net_raw=ep
```

As workaround i have pre_task that removes this capability before running the role.

**Comment by SuperQ** [comment]
**This role has been deprecated in favor of a the [prometheus-community/ansible](https://github.com/prometheus-community/ansible) collection.**
