### ISSUE TITLE
Include package for setcap

### ISSUE THREAD

**Issue by SuperQ** [cloudalchemy/ansible-blackbox-exporter#9]
On default Debian (minimal) the `libcap2-bin` package is not installed, causing the service to not startup due to the `/sbin/setcap` command in the systemd unit.

**Comment by paulfantom** [comment]
I'm thinking about removing [this line](templates/blackbox_exporter.service.j2#L12) from systemd file and just setting capability with [ansible capabilities](http://docs.ansible.com/ansible/latest/capabilities_module.html) module after changing file permission of blackbox_exporter binary to 0750 and ownership to `blackbox-exp` system user.
It could solve this problem but I don't know if this won't cause any security related issue. @SuperQ what do you think?

**Comment by SuperQ** [comment]
Yes, setting capabilities with ansible sounds great.
